version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
  db:
    image: postgres
    environment:
      POSTGRES_DB: kikdatabase
      POSTGRES_USER: kikdatabaseuser
      POSTGRES_PASSWORD: databasepassword
    ports:
      - "5432:5432"
    networks:
      - backend
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - backend

networks:
  backend:
