version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: kikdatabase
      POSTGRES_USER: kikdatabaseuser
      POSTGRES_PASSWORD: databasepassword
    ports:
      - "5432:5432"
